### PR TITLE
Update Install-WindowsSdkISO.ps1

### PR DESCRIPTION
**Pull request by beweedon**
This updates the file to the version introduced in
https://github.com/microsoft/microsoft-ui-xaml/pull/3095. That PR fixed
some bugs in the script, such as the ISO not actually being unmounted
after use.

### CODE REVIEW

**Comment by beweedon** [comment]
I'm kinda hoping this will maybe fix out "out of space" build issue

**Comment by beweedon** [comment]
Going to temporarily change the SDK version here to test this.

**Comment by beweedon** [comment]
Alas no luck in fixing the bug

**Comment by beweedon** [comment]
The build issue has been fixed in #62. This will be ready to check in once that PR is completed and this one is rebased.

**Review by zhayuli — APPROVED** [review]

**Pull request merged**
